<a href="https://colab.research.google.com/github/EricoGSilva/APS_Metodos_Numericos/blob/main/Quest%C3%A3o_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[3, 2, 7], [2, 5, 7], [7, 1, 8]])

autovalores, autovetores = np.linalg.eig(A)

print("Autovalores: ", autovalores)
print("Autovetores: ", autovetores)


Autovalores:  [14.35631335 -1.47439425  3.11808089]
Autovetores:  [[-0.49765377 -0.71770766 -0.05354039]
 [-0.58529731 -0.39690103 -0.96038303]
 [-0.64013107  0.57215844  0.27349199]]


In [ ]:
import numpy as np

A = np.array([[3, 2, 7], [2, 5, 7], [7, 1, 8]])

U, s, Vt = np.linalg.svd(A)

print("Matriz U: ", U)
print("Matriz S: ", s)
print("Matriz V transposta: ", Vt)

Matriz U:  [[-0.51122121 -0.08505854 -0.85522975]
 [-0.53607734 -0.74623202  0.39466297]
 [-0.67176928  0.66022937  0.33589168]]
Matriz S:  [15.29608356  4.36493456  0.98852112]
Matriz V transposta:  [[-0.47778264 -0.28599467 -0.83062073]
 [ 0.6584213  -0.74251922 -0.12307149]
 [ 0.58155407  0.6056998  -0.54306778]]
